# Generated by Django 4.1.1 on 2025-11-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0018_auto_20240827_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pokemon_images/', verbose_name='Изображение покемона'),
        ),
    ]
